### ISSUE TITLE
specify test release path through conda_setup.

### ISSUE THREAD

**Issue by davidslac** [slaclab/anarel-manage#3]
@slaclab/psdm and @chrisvam  would like to specify a test release through conda_setup. Now your current directory has to be a test release for it to work.

I have added this feature, it is in production. Do

source conda_setup --reldir /path/to/my/testrelease

please try, close if looks good.

**Comment by chrisvam** [comment]
Thanks for implementing this very useful feature, David.  I see the following when I don't do the command in the test-release directory:

psanagpu103:~$ pwd
/reg/neh/home/cpo
psanagpu103:~$ source conda_setup --reldir ~/testconda/
detected conda release directory.
activating a production conda environment with command source activate ana-1.0.7
environment setup. Type: undo_conda  [return] at the prompt to undo.
(ana-1.0.7) *tr* psanagpu103:~$ printenv LD_LIBRARY_PATH
/reg/neh/home4/cpo/arch/x86_64-rhel7-gcc48-opt/lib:
(ana-1.0.7) *tr* psanagpu103:~$ 

I think LD_LIBRARY_PATH should have "testconda" in it, more like this:

 ~cpo/testconda/arch/x86_64-rhel7-gcc48-opt/lib/

It works if I do the conda_setup command in the test-release directory.

chris
