### ISSUE TITLE
ndarray 1.1.7 is not building

### ISSUE THREAD

**Issue by davidslac** [slaclab/anarel-manage#34]
To build this right now, as psreldev, one goes to where I have checked out the git branch, and does
```
(manage) (psreldev) psel701: /reg/g/psdm/sw/conda/manage-git $ ana-rel-admin --cmd bld-pkg --recipe recipes/psana/ndarray
```
That is, go to manage-git, and run this admin command, but  point to the recipe in the git branch. This has to be done on psel701, psdev105 and psdev106. 

The error includes 
```
Warning: failed to download source.  If building, will try again after downloading recipe dependencies.
Error was: 
Command '['/reg/g/psdm/sw/conda/inst/miniconda2-dev-rhel6/envs/ana-1.2.2/bin/git', 'checkout', '1.1.7']' returned non-zero exit status 1
Traceback (most recent call last):
```
do we have the tag correct?

**Comment by weninc** [comment]
I hoped I fixed this by changing the version in ndarray to match our pattern in the git branch.
