### ISSUE TITLE
Matplotlib dependency of packages in die anaconda repo

### ISSUE THREAD

**Issue by fzimmermann89** [slaclab/anarel-manage#57]
Hi,

I dont know if this is the right place to ask about the conda repo lcls-rhel7, if anybody knows a better plqce, please let me know..

The psana-conda package published in lcls-rhel7 has a matplotlib dependency where an exact build is specified (not only a version). This build is neither in the lcls-rhel7 repo, nor anaconda nor conda-forge - I cant find the specified build anywhere. 

Whats the reasoning behind this dependency? Can you loosen it to a version or supply the matplotlib build as well?

Thanks
Felix

**Comment by weninc** [comment]
I uploaded our specific matplotlib package to the lcls-rhel7 channel.
